# Generated by Django 5.2.3 on 2025-08-07 13:02

import django.db.models.deletion
import posts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialshare',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='social_shares/media/', validators=[posts.models.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialshare',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('shared', 'SHARED'), ('failed', 'FAILED')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_status', models.CharField(choices=[('pending', 'pending'), ('shared', 'shared'), ('failed', 'failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='posts.post')),
            ],
        ),
    ]
